Arithmetic with R

```{r}
5+5-2
3*5
(2+2)*4-2
28%%6
8%%3
```

Variable assignment
 = or <-
```{r}
x <- 2
x

y <- 9

result <- x-y
result

```
Basics data types in R

```{r}

my_numeric <- 423
my_character <- "universe"
my_logical <- FALSE

class(my_numeric)
class(my_character)
class(my_logical)

```

Create a vector
``` {r}

numeric_vector <- c(1,10,49)
numeric_vector

character_vector <- c("a","b","c")
character_vector

boolean_vector <- c(TRUE,FALSE,TRUE)
boolean_vector

poker_vector <- c(140,-30,-20,-130,240)
roulette_vector <- c(-24, -50, 10,350,10)

poker_vector
```
Naming a vector
```{r}
names(poker_vector) <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
poker_vector

names(roulette_vector) <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
roulette_vector

days <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
names(poker_vector) <- days
poker_vector
```
Selection by comparison
```{r}
age <- 17
age >=18

selection_vector <- poker_vector > 0
selection_vector 


poker_winning_days <- poker_vector[selection_vector]
poker_winning_days
```
Calculating
```{r}
x_vector <- c(4,7,9)
y_vector <- c(12,45,78)

result_vector <- y_vector+x_vector
result_vector
```


Clase 2
vector selection 
```{r}
poker_vector
poker_vector[3]
poker_vector[1:5]
poker_vector[c(2,3,4)]
```
Matrices
```{r}
matrix(1:9, byrow=TRUE, nrow=3)
```
Analyze matrices
```{r}
new_hope <- c(460.998,314.4)
empire_strikes <- c(290.475,247.900)
return_jedi <- c(309.306,165.8)

box_office <- c(new_hope, empire_strikes, return_jedi)
box_office

star_wars_matrix <- matrix(box_office, byrow=TRUE, nrow=3) 
star_wars_matrix

```
Nombrar rows and columns
```{r}
region <-c("US","non-US");
titles <- c("A new hope", "The empire strikes back","Return of the Jedi");
colnames(star_wars_matrix) <- region

rownames(star_wars_matrix) <-  titles
star_wars_matrix
```
sumar rows
```{r}
rowSums(star_wars_matrix)
colSums(star_wars_matrix)
```


cbind and rbind - añadir columna y fila
```{r}
total_revenue_by_title <- rowSums(star_wars_matrix)
total_revenue_by_region <- colSums(star_wars_matrix)

total <- cbind(star_wars_matrix,total_revenue_by_title)
total <- rbind(total, total_revenue_by_region)

total
```
```{r}
star_wars_matrix
star_wars_matrix[1,2]
star_wars_matrix[1:2,2]
star_wars_matrix[1:2,1:2] ## un rango

star_wars_matrix[c(1,3),1] # primer arreglo indica filas a elegir

star_wars_matrix[c(1,3),] # segundo parametro vacio para seleccionar todos
total[1:3,2:4]
```
```{r}
mean <- star_wars_matrix/5 #divide la matriz entre 5

mean*2
```
Factores

```{r}
sex_vector <- c("Male","Female","Female","Male","Male")
factor_sex_vector <- factor(sex_vector)
factor_sex_vector # OUTPUT: Levels: Female Male
```

```{r}
temperature_vector <- c("High","Low","High","Low","Medium")
factor_temperature_vector <- factor(temperature_vector, order=TRUE,levels = c("Low","Medium","High"))

factor_temperature_vector
```

Factor levels
```{r}
survey_vector <- c("M","F","F","M","M")
factor_survey_vector <- factor(survey_vector)
factor_survey_vector

levels(factor_survey_vector) <- c("Female","Male")
```
```{r}
summary(factor_survey_vector) #Cantidad de elementos por categorias
```

Factores Ordenados
```{r}
male <- factor_survey_vector[1] # Male from survey_vector
female <- factor_survey_vector[2]

male>female #No funciona sin ordenamiento

speed_vector <- c("medium","slow","slow","medium","fast")
factor_speed_vector <- factor(speed_vector, ordered=TRUE, levels = c("slow","medium","fast"))

factor_speed_vector

speed_1 <- factor_speed_vector[2]
speed_5 <- factor_speed_vector[5]
speed_1 < speed_5 #Funciona para ordinales
speed_5 > speed_1
```




